import styles from "./Features.module.css"

const Features = () => {

    // eslint-disable-next-line react/prop-types
    function IconTitleText({ icon, title, text }) {
        return (
            <div className={styles.feature}>
                <img 
                    src={icon} 
                    alt=""
                    aria-hidden="true" 
                    className={styles.icon}
                />
                <p className={styles.subtitle}>{title}</p>
                <p className={styles.description}>{text}</p>
            </div>
        );
    }

    return (
        <section className={styles.features}>
            <h2 className={styles.title}>Features</h2>
            <div className={styles.wrapper}>
                <IconTitleText 
                    icon={"images/note.svg"}
                    title={"Sturectured Note"}
                    text={
                        "A strucutred note generated by capturing the information on Youtube video's transcript."
                    }
                />
                <IconTitleText 
                    icon={"images/quesiton.svg"}
                    title={"Cue Questions"}
                    text={
                        "Nova generates cue questions for your study note to improve racall to information."
                    }
                />
                <IconTitleText 
                    icon={"images/summary.svg"}
                    title={"Summary"}
                    text={
                        "Finally a summary is generated to sum it all up."
                    }
                />
            </div>
        </section>
    )
}

export default Features